name: "\U0001F4A5 Build error"
description: Unable to build ReSolve
title: "Build issue: "
labels: [build-error]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: CMake error message(s)
      description: |
        Fill in the console output when you try to build.
      value: |
        ```console
        $ make
        ...
        ```
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Information on your system or the test runner
      description: Please include your system information, including operating system,
      compilers, hardware backends (CUDA, HIP), dependencies, and required package versions.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If you have any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.) you can add that here as well.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: |
        Please upload test logs or any additional information about the problem.
